name: Quality Checks

on: [push, pull_request]

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Static Code Analysis
        run: |
          npm run lint
          npm run prettier:check
    
      - name: Performance Testing
        run: |
          npx lighthouse https://localhost:4200 --output=json --output-path=./reports/lighthouse-report.
          
      - name: Unit and Integration Testing
        run: |
          npm run test
          npm run test:ci

      
