quality_criteria:
  static_code_analysis:
    tools:
      - ESLint
      - Stylelint
      - Prettier
    scripts:
      - npm run lint
      - npm run prettier:check
  
  unit_and_integration_testing:
    tools:
      - Jasmine
      - Karma
      - Cypress
    scripts:
      - npm run test
      - npm run test:ci
      - npm run cypress:open
      - npm run cypress:run
  
  security_scanning:
    tools:
      - npm audit
      - eslint-plugin-security
    scripts:
      - npm audit --production
      - eslint --plugin security "src/**/*.ts"
  
  performance_testing:
    tools:
      - Lighthouse
      - WebPageTest
    scripts:
      - npx lighthouse https://localhost:4200 --output=json --output-path=./reports/lighthouse-report.json
